package com.example.coffepitstop;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Build;
import android.os.Bundle;
import android.os.StrictMode;
import android.support.wearable.activity.WearableActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.amazonaws.auth.AWSSessionCredentials;
import com.amazonaws.auth.CognitoCachingCredentialsProvider;
import com.amazonaws.auth.CognitoCredentialsProvider;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;

import com.amazonaws.services.sns.AmazonSNSAsyncClient;
import com.amazonaws.services.sns.AmazonSNSClient;
import com.amazonaws.services.sns.model.CreatePlatformEndpointRequest;
import com.amazonaws.services.sns.model.CreatePlatformEndpointResult;
import com.amazonaws.services.sns.model.CreateTopicRequest;
import com.amazonaws.services.sns.model.PublishRequest;
import com.amazonaws.services.sns.model.PublishResult;
import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.InstanceIdResult;

public class MainActivity extends WearableActivity {

    private static final String PUSH_SETTINGS = "PushController.PUSH_SETTINGS";
    private static final String PUSH_SETTINGS_KEY = "PushController.PUSH_SETTINGS_KEY";
    private CognitoCredentialsProvider credentialsProvider;
    private AWSSessionCredentials awsSessionCredentials;
    private AmazonSNSClient snsClient;
    private String token;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        if( Build.VERSION.SDK_INT >= 9){
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder().permitAll().build();

            StrictMode.setThreadPolicy(policy);
        }

        //String token = FirebaseInstanceId.getInstance().getToken();


        FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener( new OnSuccessListener<InstanceIdResult>() {
            @Override
            public void onSuccess(InstanceIdResult instanceIdResult) {
                token = instanceIdResult.getToken();
                // Do whatever you want with your token now
                // i.e. store it on SharedPreferences or DB
                // or directly send it to server

                if(token == null)
                    Log.d("TOKEN","NULL");
                else
                    Log.d("TOKEN",token);

                initialSetup();
            }
        });


        final Button button = findViewById(R.id.button);
        button.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Log.d("BUTTON", "Premuto");
                // Code here executes on main thread after user presses button

                //TODO: topic arn is hardcoded for the moment. Needs to be replaced
                String topicArn = "arn:aws:sns:us-east-1:341434091225:Arg1";
                // Publish a message to an Amazon SNS topic.
                final String msg = "If you receive this message, publishing a message to an Amazon SNS topic works.";

                //PublishRequest creates the request that is sent with the next method publish()
                final PublishRequest publishRequest = new PublishRequest(topicArn, msg);
                final PublishResult publishResponse = snsClient.publish(publishRequest);

                // Print the MessageId of the message.
                System.out.println("MessageId: " + publishResponse.getMessageId());
            }
        });

    }

    private String retrieveEndpointArn() {
        final SharedPreferences sharedPreferences =
                this.getSharedPreferences(PUSH_SETTINGS, Context.MODE_PRIVATE);
        return sharedPreferences.getString(PUSH_SETTINGS_KEY, null);
    }

    private void storeEndpointArn(String endpointArn) {
        final SharedPreferences.Editor sharedPreferencesEditor =
                this.getSharedPreferences(PUSH_SETTINGS, Context.MODE_PRIVATE).edit();
        sharedPreferencesEditor.putString(PUSH_SETTINGS_KEY, endpointArn).apply();
    }

    private void initialSetup(){
        credentialsProvider = new CognitoCredentialsProvider(
                "us-east-1:5223d77f-b704-4027-97e2-d6c837276cdb", // ID pool di identità
                Regions.US_EAST_1 // Regione
        );

        if (credentialsProvider == null)
            System.out.println("Credential is null");
        else
            System.out.println("Credential is not null ");

        //Aws credentials are generated by Cognito
        awsSessionCredentials = credentialsProvider.getCredentials();

        System.out.println(awsSessionCredentials.getAWSAccessKeyId() + " and " + awsSessionCredentials.getAWSSecretKey());



        //SNS client is created from the previous credentials
        snsClient = new AmazonSNSClient(awsSessionCredentials);
        snsClient.setRegion(Region.getRegion(Regions.US_EAST_1));

        if (retrieveEndpointArn() == null) { //Platform endpoint does not exist

            //Se we just create a new one
            CreatePlatformEndpointRequest platformEndpointRequest = new CreatePlatformEndpointRequest();
            platformEndpointRequest.setCustomUserData("LORICELLI NUOVO");
            platformEndpointRequest.setToken(token);
            platformEndpointRequest.setPlatformApplicationArn("arn:aws:sns:us-east-1:341434091225:app/GCM/CoffeePitStop");
            CreatePlatformEndpointResult platformEndpointResult = snsClient.createPlatformEndpoint(platformEndpointRequest);

            //We store the newly created endpoint
            storeEndpointArn(platformEndpointResult.getEndpointArn());


            Log.d("ENDPOINT", "Endpoint created " + platformEndpointResult.getEndpointArn());
        } else
            Log.d("ENDPOINT","Endpoint already existing.");

    }
}
